---
title: "Assignment 02"
output: html_document
date: "2022-10-05"
---

## Assignment 02 

```{r}
rm(list=ls())
library(tidyverse)
library(Stat2Data)


data("Hawks")
select(Hawks,Wing,Weight,Tail)
hSF <- select(Hawks,Wing,Weight,Tail)
print(head(Hawks))
hSF <- Hawks %<% filter(Species=="RT"&&Weight>=1000)
hSF <- Hawks %>% filter(Species=="RT"&&Weight>=1000)
hSF <- Hawks %<% filter(Species=="RT") %<% filter(Weight>=1000)
?filter
hSF <- Hawks %>% filter(Species=="RT"&Weight>=1000)
hSF <- Hawks %>% filter(Species=="RT"&Weight>=1000) %>% select(Wing,Weight,Tail)
print(hSF)
arrange(hSF)
head(sort(hSF))
head(arrange(hSF))
?arrange
head(arrange(hSF,Wing))
head(Hawks)
hawkSpeciesNameCodes <- data.frame(['CH','RT','SS',"Cooper's","Red-tailed","Sharp-shinned"])
hawkSpeciesNameCodes <- data.frame(c('CH','RT','SS'),c("Cooper's","Red-tailed","Sharp-shinned"))
print(head(hawkSpeciesNameCodes))
hawkSpeciesNameCodes <- data.frame(species_code<-c('CH','RT','SS'),species_name_full<-c("Cooper's","Red-tailed","Sharp-shinned"))
print(head(hawkSpeciesNameCodes))
species_code<-c('CH','RT','SS')
species_name_full<-c("Cooper's","Red-tailed","Sharp-shinned")
hawkSpeciesNameCodes <- data.frame(species_code,species_name_full)
print(hawkSpeciesNameCodes))
print(hawkSpeciesNameCodes)
?rename
print(head(Hawks))
rename(hawkSpeciesNameCodes,c(species_code="Species"))
rename(hawkSpeciesNameCodes,c("species_code"="Species"))
rlang::last_error()
rename(hawkSpeciesNameCodes,species_code="Species")
rename(hawkSpeciesNameCodes,species_code=Species)
View(hawkSpeciesNameCodes)
View(hawkSpeciesNameCodes)
View(hawkSpeciesNameCodes)
rename(hawkSpeciesNameCodes,species_code=Species)
View(hawkSpeciesNameCodes)
rename(hawkSpeciesNameCodes,species_code="Species")
awkSpeciesNameCodes<-rename(hawkSpeciesNameCodes,species_code="Species")
awkSpeciesNameCodes<-rename(hawkSpeciesNameCodes,Species=species_code)
hawkSpeciesNameCodes<-rename(hawkSpeciesNameCodes,Species=species_code)
rm(awkSpeciesNameCodes)
tmp <- left_join(Hawks,hawkSpeciesNameCodes)
print(head(tmp))
tmp <- select(Hawks,-Species)
tmp <- rename(Hawks,Species=species_name_full)
tmp <- rename(Hawks,Species=all_of(species_name_full))
rm(species_name_full)
rm(species_code)
tmp <- rename(Hawks,Species=all_of(species_name_full))
tmp <- rename(Hawks,Species=
species_name_full)
print(head(tmp)
print(head(tmp))
print(head(tmp))
tmp <-rename(Hawks,hawkSpeciesNameCodes)
rlang::last_error()
tmp <- left_join(Hawks,hawkSpeciesNameCodes)
hawksFullName <- select(tmp,species_name_full,Wing,Weight)
head(hawksFullName)
?mutae
?mutate
hawksWithBMI <- Hawks %>% mutate(bird_BMI) %>% select(Species,bird_BMI)
hawksWithBMI <- Hawks %>% mutate(bird_BMI=1000*Weight/Wing/Wing) %>% select(Species,bird_BMI)
print(head(hawksWithBMI,8))
print(head(arrange(hawksWithBMI,bird_BMI),8))
?arrange
print(head(arrange(hawksWithBMI,desc(bird_BMI),8))
print(head(arrange(hawksWithBMI,desc(bird_BMI),8)))
print(head(arrange(hawksWithBMI,desc(bird_BMI)),8))
?summarize
num_rows <- Hawks %>% group_by(Species) %>% summarise(row)

### 1.5 
Hawks %>% group_by(Species) %>% summarise(num_rows=n(),mn_wing=mean(Wing,na.rm=TRUE),md_wing=median(Wing,na.rm=TRUE),t_mn_ting=mean(Wing,trim=0.1),b_wt_ratio=max(Wing/Tail,na.rm=TRUE))

tmp <- Hawks %>% group_by(Species) %>% summarise(across(9:Crop,~sum(is.na(.x))))
> print(tmp)
```



```{r}
impute_by_mean<-function(x){
mu<-mean(x,na.rm=1) # first compute the mean of x
impute_f<-function(z){ # coordinate-wise imputation
if(is.na(z)){
return(mu) # if z is na replace with mean
}else{
return(z) # otherwise leave in place
}
}
return(map_dbl(x,impute_f)) # apply the map function to impute across vector
}
```

```{r}
impute_by_median<-function(x){
mu<-median(x,na.rm=1) # first compute the mean of x
impute_f<-function(z){ # coordinate-wise imputation
if(is.na(z)){
return(mu) # if z is na replace with mean
}else{
return(z) # otherwise leave in place
}
}
return(map_dbl(x,impute_f)) # apply the map function to impute across vector
}
```

```{r}
df_xy<-function(x){
  tmp<- seq(0,10,by=0.1)
  tmp2<- tmp*5+1
  return(data.frame(tmp[1:x-1],tmp2[1:x-1]))
}

```

```{r}
x <- seq(0,10,by=0.1)
y <- x*5+1
df_xy <- data.frame(x,y)
df_xy %>% head(5)
```

```{r}
sometimes_missing<- function(x,y){
  if(x%%5==0) return(NA)
  
  return(y)
}
```

```{r}
df_xy_missing <- df_xy %>% mutate(y=map2_dbl(seq(101),y<-x*5+1,~sometimes_missing(.x,.y)))


df_xy_imputed <- df_xy_missing %>% mutate(y=impute_by_median(df_xy_missing$y))

```

```{r}
file_name<-"HockeyLeague.xlsx"
folder_path<-"/Users/syo/Downloads/"
file_path<-paste(folder_path,file_name,sep="")
wins_data_frame<-read_excel(file_path,sheet="Wins")



wins_tidy <- pivot_longer(data = wins_data_frame,
cols = '1990':'2020',
names_to = "year",
values_to = "sp_count")
colnames(wins_tidy)[1] = 'species'
wins_tidy <- separate(wins_tidy, sp_count ,c("Wins","Total"),sep=" of ",convert = TRUE)

wins_tidy %>% dim()

```

```{r}
losses_tidy <- pivot_longer(data = losses_data_frame,
cols = '1990':'2020',
names_to = "year",
values_to = "sp_count")
colnames(losses_tidy)[1] = 'species'
losses_tidy <- separate(losses_tidy, sp_count ,c("Losses","Total"),sep=" of ",convert = TRUE)

losses_tidy %>% dim()
```

```{r}
hockey_df <- inner_join(losses_tidy,wins_tidy)
colnames(hockey_df)[1] = 'Team'
colnames(hockey_df)[2] = 'Year'
hockey_df <- hockey_df %>% mutate(Draws=Total-Wins-Losses)
hockey_df <-hockey_df %>% mutate(Wins_rt=Wins/Total)
hockey_df <- hockey_df %>% mutate(Losses_rt=Losses/Total)
hockey_df <- hockey_df %>% mutate(Draws_rt=Draws/Total)
```




```{r}
hockey_df %>% group_by(Team) %>% summarise(W_md=median(Wins_rt),W_mn=mean(Wins_rt),L_md=median(Losses_rt),L_mn=mean(Losses_rt),D_md=median(Draws_rt),D_mn=mean(Draws_rt)) %>% arrange(desc(W_md))
```

```{r}
> univar_plot <- wins_tidy %>% filter(species=="Ducks") %>% ggplot(aes(x=Wins))+xlab("Wins")
> univar_plot+geom_histogram(binwidth = 1)+ylab("Count")
```
