---
title: "Assignment 6"
author: "Siyu Yang"
date: "2022-11-09"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r load-packages, include=FALSE}
library(dplyr)
library(magrittr)
library(knitr)
library(tidyverse)
```
# 1. Continuous random variables and limit laws

## 1.1 (Q1)

$$
P(U \in [a, b]) = F(b)-F(a) = \int_{a}^{b}p(x)dx =b - a.
$$

## 1.1 (Q2)

```{r}
n <- 1000
sample_X <- data.frame(U=runif(n)) %>%
mutate(X=case_when(
(0<=U)&(U<0.25)~3,
(0.25<=U)&(U<0.5)~10,
(0.5<=U)&(U<=1)~0)) %>%
pull(X)
```

## 1.1 (Q3)

```{r}
sample_X_0310 <- function(a,b,n){
  sample_X <- data.frame(U=runif(n)) %>%
    mutate(X=case_when(
      (0<=U)&(U<a)~3,
      (a<=U)&(U<a+b)~10,
      (a+b<=U)&(U<=1)~0))%>%
    pull(X)
  return(sample_X)
  
}
```

## 1.1 (Q4)

```{r}
sample_X_2 <- sample_X_0310(0.5,0.1,10000)
weighted.mean(sample_X_2)
```

result is close to 2.5.

    [1] 2.504

## 1.1 (Q5)

```{r}
sample_variance <- var(sample_X_2)
population_variance <- 9999/10000*var(sample_X_2)
```

## 1.1 (Q6)

```{r}
#set.seed(NULL)
alpha <- 0.1
beta <- seq(0,0.9,0.01)
n <- 100
seq91<- seq(91)
sample_list <- list()
sample_mean <- list()
for(i in seq91){sample_list[[i]] <- sample_X_0310(alpha,beta[i],n)}
for(i in seq91){sample_mean[[i]]<- mean(sample_list[[i]])}
#test <- data.frame(beta,sample_list)

data <- data.frame(beta) %>% 
  mutate(sample_X=sample_list) %>% 
  mutate(samplemean=sample_mean) %>% 
  mutate(expectation=beta*10+alpha*3)


```

## 1.1 (Q7)

```{r}
p<-ggplot()+
  geom_point(data = data,aes(x=beta,y=expectation),colour='red')
data$samplemean <- unlist(data$samplemean)
p<-p+geom_point(data = data,aes(x=beta,y=samplemean),colour='blue')

p
```

## 1.2 (Q1)

$$
F(x) = 1-e^{-\lambda{x}}
$$

## 1.2 (Q2)

```{r}

my_cdf_exp <- function(x,lambda){
  if(x<0) return(0)
  return(1-exp(-lambda*x))
}

lambda <- 1/2
map_dbl(.x=seq(-1,4), .f=~my_cdf_exp(x=.x,lambda=lambda) )
```

```{r}
test_inputs <- seq(-1,10,0.1)
my_cdf_output <- map_dbl(.x=test_inputs, .f=~my_cdf_exp(x=.x,lambda=lambda))
inbuilt_cdf_output <- map_dbl(.x=test_inputs,.f=~pexp(q=.x,rate=lambda))
all.equal(my_cdf_output,inbuilt_cdf_output)
```

## 1.2 (Q3)
```{r}
my_quantile_exp<- function(p,lambda)
  
```


## 1.3 (Q1)

# 2. Location estimators with Gaussian data

## 2 (Q1)

....

## 2 (Q2)

....

# 3. (\*\*) The law of large numbers and Hoeffding's inequality

## 3 (Q1)
