---
title: "Assignment07"
output: pdf_document
date: "2022-11-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
RedTailedDf <- Hawks %>% filter(Species=="RT") %>%
  select(Weight, Tail, Wing)


n = length(RedTailedDf$Tail)
mu_mle <- mean(RedTailedDf$Tail, na.rm=TRUE)
sigma_mle <- sd(RedTailedDf$Tail, na.rm=TRUE) * sqrt(n/(n-1))
sigma_squared_mle <- sigma_mle^2;
```

```{r}
# indices
len <- seq(mu_mle-3*sigma_mle, mu_mle+3*sigma_mle, sigma_mle*0.001)
# plot estimated density function
color <- c("MLE density"="red", "Kernel density"="blue")
estimated_density <- data.frame(Length=len, Density=dnorm(len, mean=mu_mle, sd=sigma_mle))
plot_obj <- ggplot() + geom_line(data=estimated_density,
                                 aes(x=Length, y=Density, color="MLE density"))
# kernel density plot of the sample
plot_obj + geom_density(data=RedTailedDf,
                        aes(x=Tail, color="Kernel density")) +
  labs(y="Tail length (mm)") +
  theme_bw() + scale_color_manual(values = color)
```

```{r}
set.seed(0)
sample_size_seq <- seq(5, 100, 5)
num_trials_per_size <- 1000
mu_0 <- 1
sigma_0 <- 3
compute_V_mle <- function(x){ return(mean((x-mean(x))^2)) }; compute_V_U <- function(x){
  n <- length(x)
  return (compute_V_mle(x)*n/(n-1))
}
df <- crossing(sample_size=sample_size_seq, trials=seq(num_trials_per_size) ) %>% # create samples
mutate(samples = map(sample_size, ~rnorm(.x, mean = mu_0, sd = sigma_0) ) ) %>% # compute V_mle
mutate(V_mle = map_dbl(samples, compute_V_mle)) %>% # compute V_U
mutate(V_U = map_dbl(samples, compute_V_U))
# compute bias
df_bias <- df %>% group_by(sample_size) %>%
  summarise(V_mle_bias=mean(V_mle)-sigma_0^2, V_U_bias=mean(V_U)-sigma_0^2)

```


```{r}
df_bias_longer <- df_bias %>%
pivot_longer(c(V_mle_bias, V_U_bias), names_to = 'Estimator', values_to = 'Bias' ) %>%  mutate(Estimator=case_when(Estimator=='V_mle_bias'~'MLE',
                             Estimator=='V_U_bias'~'Unbiased estimator'))
df_bias_longer %>% ggplot(aes(x=sample_size, y=Bias, color=Estimator)) + geom_line() +
  theme_bw() + xlab('Sample Size')

```

```{r}
set.seed(0)
sample_size_seq <- seq(5, 100, 5)
num_trials_per_size <- 10000
mu_0 <- 1
sigma_0 <- 3
compute_V_mle <- function(x){ return( mean( (x-mean(x))^2 ) ) }; compute_V_U <- function(x){
  n <- length(x)
  return (compute_V_mle(x)*n/(n-1))
}
df <- crossing(sample_size=sample_size_seq, trials=seq(num_trials_per_size) ) %>% # create samples
mutate(samples = map(sample_size, ~rnorm(.x, mean = mu_0, sd = sigma_0) ) ) %>% # compute V_U_sqrt
mutate(V_U_sqrt = map_dbl(samples, ~sqrt(compute_V_U(.x) ))) # compute bias
df_bias <- df %>% group_by(sample_size) %>%
  summarise(V_U_sqrt_bias=mean(V_U_sqrt)-sigma_0)
```

```{r}
df_bias_longer <- df_bias %>%
pivot_longer(c(V_U_sqrt_bias), names_to = 'Estimator', values_to = 'Bias' ) %>% mutate(Estimator=case_when(Estimator=='V_U_sqrt_bias'~'sqrt(V_U)'))
df_bias_longer %>% ggplot(aes(x=sample_size, y=Bias, color=Estimator)) + geom_line() +
  theme_bw() + xlab('Sample Size')

```

```{r}
lambda_0 = 0.5
num_trials_per_sample_size=1000
df = crossing(sample_size=seq(10, 1000, 10), trials=seq(num_trials_per_sample_size)) %>% # create samples
mutate(samples=map(sample_size, ~rpois(.x, lambda_0)) ) %>%
# compute MLE
  mutate(lambda_mle = map_dbl(samples, ~mean(.x)))
df_mse <- df %>% group_by(sample_size) %>%
  summarise(mse=mean( (lambda_mle-lambda_0)^2 ))
ggplot() + geom_line(data=df_mse, aes(x=sample_size, y=mse)) +
  theme_bw() + xlab('Sample Size')
```


```{r}
real_data <- read.csv("VonBortkiewicz.csv")
# note: if the .csv file is not in your current folder, then # you will need to specify the folder where this file is in.
# MLE:
lambda_mle <- mean(real_data$fatalities )
print(lambda_mle)

```

```{r}
predict_prob_no_fatalities <- dpois(0, lambda_mle)
print(predict_prob_no_fatalities)
```

```{r}
set.seed(0)
lambda_0 = 0.5
sample_size <- 1000
df <- data.frame(trials=seq(1000)) %>%
# create samples
mutate(sample= map(trials, ~rpois(sample_size, lambda_0))) %>% # compute MLE
mutate(MLE = map_dbl(sample, mean) ) %>%
# the quality of interest
mutate(quantity = sqrt(sample_size/lambda_0)*(MLE-lambda_0) )
# create kernel density plot
ggplot(df, aes(x=quantity) ) + geom_density() +
  theme_bw()
```

```{r}
CustomerPurchase <- read.csv("CustomerPurchase.csv")
# note: if the .csv file is not in your current folder, then # you will need to specify the folder where this file is in.
CustomerPurchase <- CustomerPurchase %>%
  mutate(time_diff=lead(Time)-Time)
head(CustomerPurchase)

```

```{r}
lambda_mle = 1/mean(CustomerPurchase$time_diff, na.rm=TRUE)
lambda_mle

```

```{r}

prob_excess_one_minute <- 1 - pexp(60, rate=lambda_mle)
prob_excess_one_minute
```

```{r}
alpha <- 0.05
# adelie_flippers <- 
sample_size <- length(adelie_flippers) # adelie_flippers is a given vector sample_mean <- mean(adelie_flippers)
sample_sd <- sd(adelie_flippers)
t <- qt(1-alpha/2,df=sample_size-1)
# confidence interval
confidence_interval_l <- sample_mean-t*sample_sd/sqrt(sample_size) confidence_interval_u <- sample_mean+t*sample_sd/sqrt(sample_size) confidence_interval <- c(confidence_interval_l,confidence_interval_u) confidence_interval

```

```{r}

weights <- Hawks %>% filter(Species=="RT" ) %>%
select(Weight) %>%
filter(complete.cases(Weight)) %>%
# removing NAs; you can also use discard(is.na) after calling pull() 
  pull()
```

```{r}
alpha <- 0.01
sample_size <- length(weights) # adelie_flippers is a given vector 
sample_mean <- mean(weights)
sample_sd <- sd(weights)
t <- qt(1-alpha/2,df=sample_size-1)
confidence_interval_l <-sample_mean-t*sample_sd/sqrt(sample_size)
confidence_interval_u <-sample_mean+t*sample_sd/sqrt(sample_size)
confidence_interval <-c(confidence_interval_l,confidence_interval_u)
confidence_interval
```

```{r}
ggplot(data=data.frame(Weights=weights), aes(x=Weights)) + geom_density() +
  theme_bw()

```

```{r}
ggplot(data=data.frame(Weights=weights), aes(sample=Weights)) + stat_qq() +
  theme_bw() + stat_qq_line(color="blue")

```

```{r}
Hawks%>%filter(Species=="RT")%>%nrow()

```

```{r}
student_t_confidence_interval<-function(sample,confidence_level){ sample<-sample[!is.na(sample)] # remove any missing values 
n<-length(sample) # compute sample size
mu_est<-mean(sample) # compute sample mean
sig_est<-sd(sample) # compute sample sd
alpha = 1-confidence_level # alpha from gamma
t<-qt(1-alpha/2,df=n-1) # get student t quantile 
l=mu_est-(t/sqrt(n))*sig_est # lower 
u=mu_est+(t/sqrt(n))*sig_est # upper
return(c(l,u))
}

```

```{r}
num_trials <- 100000
sample_size <- 30
mu_0 <- 1
sigma_0 <- 3
alpha <- 0.05
set.seed(0) # set random seed for reproducibility

single_alpha_coverage_simulation_df <- data.frame(trial=seq(num_trials)) %>%
  # generate random Gaussian samples:
  mutate(sample=map(.x=trial,.f=~rnorm(n=sample_size,mean=mu_0,sd=sigma_0))) %>% 
  # generate confidence intervals:
  mutate(ci_interval=map(.x=sample, .f=~student_t_confidence_interval(.x,1-alpha)))%>% 
  # check if interval covers mu_0:
  mutate(cover=map_lgl(.x=ci_interval, .f=~((min(.x)<=mu_0)&(max(.x)>=mu_0))))%>%
  # compute interval length:
  mutate(ci_length=map_dbl(.x=ci_interval, .f=~(max(.x)-min(.x))))

# estimate of coverage probability:
single_alpha_coverage_simulation_df %>%
  pull(cover) %>%
  mean()

```

```{r}
probs_CI_contains_mu <- function(gamma){ 
num_trials <- 100000
sample_size <- 30
mu_0 <- 1
sigma_0 <- 3
alpha <- 1-gamma
single_alpha_coverage_simulation_df <- data.frame(trial=seq(num_trials)) %>%
# generate random Gaussian samples:
  mutate(sample=map(.x=trial,.f=~rnorm(n=sample_size,mean=mu_0,sd=sigma_0))) %>% 
  # generate confidence intervals:
  mutate(ci_interval=map(.x=sample, .f=~student_t_confidence_interval(.x,1-alpha)))%>% 
  # check if interval covers mu_0:
  mutate(cover=map_lgl(.x=ci_interval, .f=~((min(.x)<=mu_0)&(max(.x)>=mu_0))))%>%

  # compute interval length:
  mutate(ci_length=map_dbl(.x=ci_interval, .f=~(max(.x)-min(.x))))

# estimate of coverage probability:
single_alpha_coverage_simulation_df %>%
  pull(cover) %>%
  mean()
}

df <- data.frame(gamma=seq(0.8,1,0.02)) %>%
  mutate(probs=map_dbl(gamma, probs_CI_contains_mu))

```

```{r}
ggplot() + geom_point(data=df, aes(x=gamma, y=probs)) +
  theme_bw()

```

