---
title: "Assignment 5"
author: "Insert My Name"
date: "2022-10-26"
output: html_document # you can change to other output format if you want
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Conditional probability, Bayes rule and independence

## 1.1 (Q1)

$$ P(A\|B) = \frac{P(B|A)*P(A)}{P(B|A)*P(A)+P(B|A^{c})*P(A^{c})}

$$

....

## 1.2 (Q1)
1. 
$$
P(A|B) = \frac{P(A)}{P(B)}
$$
when $P(B|A) = \phi $
$$
P(A|B) = \frac{P(B|A)*P(A)}{P(B)} = 0
$$

2. 
$$
P(A|B) = \frac{P(B|A)*P(A)}{P(B)}
$$

$$
P(A|B) = 0
$$


3. 
$$
P(A|B) = 1
$$

4. 
$$
P(A|\Omega) = P(A)
$$

5. 
$$
 P(A ∩ B ∩ C) = P(A | B ∩ C) · P(B | C) · P(C)
$$

6. 
$$
P(A|B ∩ C) = \frac{P(B|A∩C)·P(A|C)}{P(B|C)}
.
$$
....

## 1.2 (Q2)
0.86  
....

## 1.3 (Q1)
A, B, C are not mutually independent.

## 1.4 
If not change the door, the winning probability is 1/3.  
If change the door, the winning probability is 2/3.


# 2. Random variables and discrete random variables


## 2.2 (Q1)

1. 
$$
p_X = 3\alpha+10\beta
$$

2. 
$$
E(X) = 3\alpha+10\beta

$$

$$ 
variance = (3\alpha+10\beta-0)^2*(1-\alpha-\beta)+(3\alpha+10\beta-3)^2*\alpha+(3\alpha+10\beta-10)^2*\beta
$$ 

4. 
$$
standard\ deviation = \sqrt{variance}
$$



## 2.2 (Q2)
1. 
$$
P_X = (1-\alpha-\beta)*1_S(0)+\alpha*1_S(3)+\beta*1_S(10)
$$

2.

$$
F_X = 
\left\{  
             \begin{array}{**lr**}  
             1-\alpha-\beta, & x=0.   \\  
             \alpha, &  x=3.\\  
             \beta, &   x=10 
             \end{array}  
\right.
$$

## 2.2 (Q3)

$$
D(Y) = \sum_{i=1}^n{D(X_i)}
$$


## 2.2 (Q4)

```{r}
samples_Xi = rmultinom(50000, 2000, prob=c(0.5, 0.2, 0.3))
samples_Y = data.frame(samples_Xi[1,]*0+samples_Xi[2,]*3+samples_Xi[3,]*10)
colnames(samples_Y)<-c('Y')
# draw the plot
ggplot() + geom_bar(data = samples_Y, aes(x = Y), stat = "count")

```
